name: Main

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Increase Java heap space
        run: echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
        
      - name: Clean project
        run: ./gradlew clean
        
      - name: Run tests
        run: ./gradlew testDebugUnitTest

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.22
        if: always()
        with:
          files: app/build/test-results/testDebugUnitTest/*.xml

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Assemble
        run: ./gradlew assembleDebug
